Atm 9 update conditions config event map
nyxtechnology/automessage pull request #10
Opened 2022-03-25 16:41 UTC by gilbertoss

2022-03-28 16:50 UTC, edmargomes requested changes

2022-03-28 16:50 UTC, edmargomes commented on app/Jobs/ReceiveEvent.php
> +
Dá para apagar esse codigo?

2022-03-28 16:50 UTC, edmargomes commented on config/eventsMap.json
>        "classes": [
Não gostei muito desse nome, ele é entendivel para programador.

Mas um cara de infraestrutura não ira entender muito bem... sera que conseguimos pensar em outros nomes por exemplo: controllers-messages

2022-03-28 17:21 UTC, gilbertoss commented on config/eventsMap.json
>        "classes": [
Podemos criar um outro arquivo de configuração pra ser um "de para" dos nomes das contollers assim nem precisaria de passar o caminho todo da classe no eventsMap.json (como esta agora).
Seria algo assim @edmargomes ?
Pq mudar o nome da classe acho que não faz sentido.

2022-03-30 17:24 UTC, edmargomes approved these changes

2022-03-30 17:24 UTC, merged