System to sen mail smtp
nyxtechnology/automessage pull request #3
Opened 2022-02-23 13:45 UTC by DavidLordCaos

System to test sending emails via SMTP

2022-02-23 13:55 UTC, edmargomes requested changes

2022-02-23 13:55 UTC, edmargomes commented on app/Console/Commands/sendMailSMTP.php
> +        });
Aqui está um email fixo, isso precisa de vir do json de configurações.

Essa classe ja precisa estar integrada com o sistema de configurações.

2022-02-23 14:12 UTC, gilbertoss commented on app/Console/Commands/sendMailSMTP.php
> +        });
Não deveriamos ter uma classe de envio de email @edmargomes?
Pensando no fluxo de ação:
1. Recebe o evento, por exemplo nesse caso 'sendMail' (no metadata desse evento estaria todas as informações de remetente, templete e destinatario)
2. De acordo com o arquivo de configuração de eventos chama a classe apropriada desse evento 'sendMail'

Não entendi pra que temos esse Command.

2022-02-23 19:05 UTC, edmargomes commented on app/Console/Commands/sendMailSMTP.php
> +        });
Verdade @gilbertoss 
@DavidLordCaos command é para criação de comandos para o artisan.

O que precisamos é uma classe que dispara email a partir dos parametros que recebe. Esse parametros serão enviados pelo webhook.

@gilbertoss tem uma classe para o David ver de exemplo. Estou sentindo falta de uma documentação para quem for apoiar o projeto saber como cria outras integrações.

2022-02-24 12:12 UTC, closed without merging

2022-02-24 12:12 UTC, DavidLordCaos commented
VAi ser criado uma controller para fazer o disparo de email via SMTP